server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://127.0.0.1/db-xiaomizhou-admin
    username: root
    password: 123456
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970